version: '3.8'
services:
  db:
    image: postgres:15
    container_name: my-postgres-db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: top_leader
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d top_leader"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    image: top-test:latest
    container_name: top-leader-app
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/top_leader
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"