server:
  port: {PORT}

spring:
  cloud:
    gcp:
      sql:
        database-name: top_leader_prod
  docker:
    compose:
      enabled: false
  ai:
    openai:
      chat:
        options:
          model: gpt-4o

  datasource:
    username: top-leader-prod
    hikari:
      data-source-properties:
        socketFactory: com.google.cloud.sql.postgres.SocketFactory
        cloudSqlInstance: topleader-394306:europe-west3:top-leader-db
        enableIamAuth: false
        sslmode: disable
top-leader:
  app-url: https://topleaderplatform.io
  feedback:
    summary-limit: 1
  calendly:
    client-id: 2y-RjGqvvMeKw6SluocvUde2dklW58cAvsuU6mchbY8
    client-secrets: 3wdsTEa_kBwd4piAfuwht8ORxg9uQytPwK93bR0ql2E
    redirect-uri: https://topleaderplatform.io/login/calendly

google:
  application-name: "topleaderplatform.io"
  client:
    redirectUri: https://topleaderplatform.io/login/google
