server:
  port: {PORT}
spring:
  ai:
    openai:
      chat:
        options:
          model: gpt-4o
  datasource:
    username: top-leader
    hikari:
      data-source-properties:
        socketFactory: com.google.cloud.sql.postgres.SocketFactory
        cloudSqlInstance: topleader-394306:europe-west3:top-leader-db
        enableIamAuth: false
        sslmode: disable

top-leader:
  app-url: https://qa.topleaderplatform.io
  feedback:
    summary-limit: 1
  calendly:
    client-id: vnzwTereNrHoVzQbrJMAhQM3KRfRxUPXHNtiQ-R0KJw
    client-secrets: o2fU6bEm07cpt3ZHPiV16Enl-suS-v9bqGe_y8Yxb20
    redirect-uri: https://qa.topleaderplatform.io/login/calendly

google:
  application-name: "qa.topleaderplatform.io"
  client:
    redirectUri: https://qa.topleaderplatform.io/login/google
