server:
  port: ${PORT:8080}
  servlet:
    session:
      cookie:
        path: /
        same-site: lax
        secure: true
        http-only: true

spring:
  ai:
    openai:
      chat:
        options:
          model: gpt-5.2

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/top_leader_prod
    username: top-leader-prod
    hikari:
      minimum-idle: 5
      maximum-pool-size: 40
      connection-timeout: 5000
top-leader:
  app-url: https://topleaderplatform.io
  feedback:
    summary-limit: 1
  calendly:
    redirect-uri: https://topleaderplatform.io/login/calendly

google:
  application-name: "topleaderplatform.io"
  client:
    redirectUri: https://topleaderplatform.io/login/google

gcp:
  storage:
    enabled: true

springdoc:
  api-docs:
    enabled: false  # Disable OpenAPI docs on production
  swagger-ui:
    enabled: false  # Disable Swagger UI on production

management:
  opentelemetry:
    resource-attributes:
      "service.name": top-leader
      "service.namespace": topleader
      "deployment.environment": prod
  otlp:
    metrics:
      export:
        enabled: true
  metrics:
    tags:
      environment: prod
