server:
  port: {PORT}

spring:
  ai:
    openai:
      chat:
        options:
          model: gpt-4o
  datasource:
    username: top-leader-prod
    hikari:
      data-source-properties:
        socketFactory: com.google.cloud.sql.postgres.SocketFactory
        cloudSqlInstance: topleader-394306:europe-west3:top-leader-db
        enableIamAuth: false
        sslmode: disable
top-leader:
  app-url: https://topleaderplatform.io
  feedback:
    summary-limit: 1
  calendly:
    client-id: d0aX3ytJHPr9X2lIQMe_NUGi7V6bnpq4hhsFBllBiuE
    redirect-uri: https://topleaderplatform.io/login/calendly

google:
  application-name: "topleaderplatform.io"
  client:
    redirectUri: https://topleaderplatform.io/login/google
