server:
  port: {PORT}
spring:
  datasource:
    username: top-leader
    hikari:
      data-source-properties:
        socketFactory: com.google.cloud.sql.postgres.SocketFactory
        cloudSqlInstance: topleader-394306:europe-west3:top-leader-db
        enableIamAuth: false
        sslmode: disable

top-leader:
  app-url: https://qa.topleaderplatform.io

google:
  application-name: "qa.topleaderplatform.io"
  client:
    redirectUri: https://qa.topleaderplatform.io/login/google
