server:
  port: ${PORT:8080}

spring:
  cloud:
    gcp:
      sql:
        database-name: top_leader_prod
      logging:
        enabled: true
  docker:
    compose:
      enabled: false
  ai:
    openai:
      chat:
        options:
          model: gpt-4o

  datasource:
    username: top-leader-prod
    hikari:
      data-source-properties:
        socketFactory: com.google.cloud.sql.postgres.SocketFactory
        cloudSqlInstance: topleader-394306:europe-west3:top-leader-db
        enableIamAuth: false
        sslmode: disable
top-leader:
  app-url: https://topleaderplatform.io
  feedback:
    summary-limit: 1
  calendly:
    redirect-uri: https://topleaderplatform.io/login/calendly

google:
  application-name: "topleaderplatform.io"
  client:
    redirectUri: https://topleaderplatform.io/login/google

management:
  opentelemetry:
    resource-attributes:
      "service.name": top-leader
      "service.namespace": topleader
      "deployment.environment": prod
  otlp:
    metrics:
      export:
        enabled: true
  metrics:
    tags:
      environment: prod
