server:
  port: {PORT}
spring:
  cloud:
    gcp:
      sql:
        database-name: top_leader
      logging:
        enabled: true
  docker:
    compose:
      enabled: false
  ai:
    openai:
      chat:
        options:
          model: gpt-4o
          temperature: 1
  datasource:
    username: top-leader
    hikari:
      data-source-properties:
        socketFactory: com.google.cloud.sql.postgres.SocketFactory
        cloudSqlInstance: topleader-394306:europe-west3:top-leader-db
        enableIamAuth: false
        sslmode: disable
top-leader:
  app-url: https://qa.topleaderplatform.io
  feedback:
    summary-limit: 1
  calendly:
    redirect-uri: https://qa.topleaderplatform.io/login/calendly

google:
  application-name: "qa.topleaderplatform.io"
  client:
    redirectUri: https://qa.topleaderplatform.io/login/google
